"""
Core Enumerations for AUREV Payment Safety Agent.
"""
from enum import Enum


class FinalityState(str, Enum):
    FINAL_SUCCESS = "FINAL_SUCCESS"
    FINAL_FAILURE = "FINAL_FAILURE"
    NON_FINAL = "NON_FINAL"
    UNKNOWN = "UNKNOWN"
    CONFLICT = "CONFLICT"


class AurevDecision(str, Enum):
    WAIT = "WAIT"
    RETRY = "RETRY"
    STOP = "STOP"
    ESCALATE = "ESCALATE"


class PaymentStatus(str, Enum):
    INITIATED = "INITIATED"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    NOT_FOUND = "NOT_FOUND"


class BankStatus(str, Enum):
    NOT_REQUESTED = "NOT_REQUESTED"
    PENDING = "PENDING"
    DEBITED = "DEBITED"
    NOT_DEBITED = "NOT_DEBITED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    UNKNOWN = "UNKNOWN"


class MerchantStatus(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class GatewayStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    DOWN = "DOWN"
    UNKNOWN = "UNKNOWN"


class ServerStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    DOWN = "DOWN"
    UNKNOWN = "UNKNOWN"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EventType(str, Enum):
    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    GATEWAY_REQUEST = "GATEWAY_REQUEST"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    GATEWAY_SUCCESS = "GATEWAY_SUCCESS"
    GATEWAY_FAILED = "GATEWAY_FAILED"
    BANK_DEBIT = "BANK_DEBIT"
    BANK_FAILED = "BANK_FAILED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    PAYMENT_PROCESSING = "PAYMENT_PROCESSING"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    AUREV_DECISION = "AUREV_DECISION"
    RETRY_BLOCKED = "RETRY_BLOCKED"
    RETRY_PERMITTED = "RETRY_PERMITTED"
    RECOVERY_PERMIT_ISSUED = "RECOVERY_PERMIT_ISSUED"
    RECOVERY_PERMIT_USED = "RECOVERY_PERMIT_USED"
    RECOVERY_PERMIT_REVOKED = "RECOVERY_PERMIT_REVOKED"
    ESCALATED = "ESCALATED"
    SAFETY_MODE_ENTERED = "SAFETY_MODE_ENTERED"
    SAFETY_MODE_EXITED = "SAFETY_MODE_EXITED"
    REFUND_FLAGGED = "REFUND_FLAGGED"
    VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    USER_NOTIFIED = "USER_NOTIFIED"
    MERCHANT_NOTIFIED = "MERCHANT_NOTIFIED"


class PermitStatus(str, Enum):
    ACTIVE = "ACTIVE"
    USED = "USED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class ReconciliationState(str, Enum):
    NOT_NEEDED = "NOT_NEEDED"
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    RECONCILED_SUCCESS = "RECONCILED_SUCCESS"
    RECONCILED_FAILED = "RECONCILED_FAILED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
